flask_app/attacks/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user

#from .. import movie_client
from ..forms import AttackRegisterForm, AttackUpdate, AttackSubmit
from ..models import User, Attack
from ..utils import current_time
import dice


# create blue print
attacks = Blueprint("attacks", __name__)

#functions

@attacks.route("/", methods=["GET", "POST"])
def index():
    #index is essentially the register attack page..
    form = AttackRegisterForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        attack = Attack(
            owner=current_user._get_current_object(),
            name=form.name.data,
            type = form.type.data,
            damage = form.damage.data,
        )
        attack.save()
        return redirect(request.path)

    return render_template("index.html", form = form)


@attacks.route("/all/<username>", methods=["GET", "POST"])
def all(username):
    
    user = User.objects(username=username).first()
    attacks = Attack.objects(owner=user)

    return render_template("all.html", attacks = attacks)


@attacks.route("/calculate", methods=["GET", "POST"])
def calculate():
    output = 0
    form = AttackSubmit()
    if form.validate_on_submit() and current_user.is_authenticated:
        output = dice.roll(form.damage.data + "t")
        if "true" in form.isCrit.data:
            output = output*2
        print(output)

    return render_template("calculate.html", output= output, form = form)

@attacks.route("/about", methods=["GET", "POST"])
def about():
    return render_template("about.html")

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm
from ..models import User


# create blue print
users = Blueprint("users", __name__)

#User Stuff
@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("attacks.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("attacks.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
    )

flask_app/templates/about.html
{% extends "header.html" %}


{% block content %}


<body>

</body>


<div class = "main">


<div class="row">
    <div class="col">
        <div class = "about-page">
            <h1 class = "about title" >ABOUT</h1>
            <div class = "about text">
                <p>This site is designed by Rohan Balaji, and was primarly done so to save a set of "attacks" in terms of the dnd 5th edition table top system. The site uses most of what was listed in the class CMSC388J and uses the "dice" python package to handle the "dice calculation page". The initial plan of making this assignment with a React Frontend-while possible, was becoming increasingly difficult due to time constraints. You must be logged in to use the Calculate or Register Attack feature or to see your saved attacks.</p>
            </div>
        </div>
    </div>
</div>

</div>



{% endblock %}

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}

        
    
<div class="row">
    <div class="col">
        <form class= "form-base" action="" method="post">
            {{ username_form.csrf_token }}
            <h1 class="form-title">Hello, {{ current_user.username }}!</h1>
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>

{% endblock %}>

flask_app/templates/all.html
{% extends "header.html" %}
{% block content %}
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head> 
 



<div class = main>

{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}





<div class="container-fluid">
    
    {% for attack in attacks %}
    <div class="attack">
        <p class="attacklist {{loop.index1}}" >Attack#{{loop.index}}: {{attack.name}} | Damage type: {{attack.type}} | Damage: {{attack.damage}}  </p>
    </div>
    {% endfor %}


</div>

</div>



{% endblock %}

flask_app/templates/calculate.html
{% extends "header.html" %}
{% block content %}


<div class = main>

<div class="row">
    <div class="col">
        

        <form class= "form-base" action="" method="post">
            <h1 class = "form-title" >CALCULATE</h1>
            <p>Proper format is #d#.. 2d6 means rolling 2 six sided dice.</p>
            <p>If you want to double the dice, type "true" in the "isCrit". box</p>
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.damage.label(class="form-control-label green-text") }}
                {{ form.damage(class="form-control form-control-md") }}

                {% if form.damage.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.damage.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.isCrit.label(class="form-control-label") }}
                {{ form.isCrit(class="form-control form-control-lg") }}

                {% if form.isCrit.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.isCrit.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
            {% if output%}
            <p>Damage: {{output}}</p> 
            {% endif %}
        </form>
        
    </div>
    
</div>
</div>
{% endblock %}

flask_app/templates/header.html
{% block header %}

<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
</head>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <ul class="navbar-list">

        {% if current_user.is_authenticated %}
        <li class="navbar-item">
            <a class="navbar-brand" href="{{ url_for('attacks.all', username=current_user.username ) }}">Attacks </a>
        </li>
        {% endif %}
        <li class="navbar-item">
            <a class="navbar-brand" href="{{ url_for('attacks.index') }}">Register-Attack </a>
        </li>

        <li class="navbar-item">
            <a class="navbar-brand" href="{{ url_for('attacks.about') }}"> About </a>    
        </li>
        
        <li class="navbar-item">
            <a class="navbar-brand" href="{{ url_for('attacks.calculate') }}"> Calculate-Attack </a>        
        </li>
        
        <li class="navbar-item">
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav ml-auto">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.account') }}">
                            Account
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.logout') }}">
                            Logout
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.login') }}">
                            Login
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('users.register') }}">
                            Register
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </li>

    </ul>
    
        
    

    
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
<!--
<a class = "citation" href = "https://mini-moss.tumblr.com/post/667377949460381696/forever-twitter-instagram-print-shop"> from minimoss on tumblr </a> 
-->
<div  class="icon-base">
   
   <a href="https://www.linkedin.com/in/rohanpbalaji/" target="_blank">
        <img class = "icon" src="../static/ln.png">
   </a>
    
</div>

<div class="icon-light">
    <a href="https://www.linkedin.com/in/rohanpbalaji/" target="_blank">
        <img class = "icon" src="../static/ln2.png">
    </a>
    
</div>


{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="col">
        <form class="form-base" action="" method="post">
            <h1 class = "form-title" >REG-ATTACK</h1>
            {% if current_user.is_authenticated %}

            {{ form.csrf_token }}
            <div class="form-group">
                
                
                {{ form.name.label(class="form-control-label green-text") }}
                {{ form.name(class="form-control form-control-md") }}

                {% if form.name.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.name.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.type.label(class="form-control-label") }}
                {{ form.type(class="form-control form-control-lg") }}

                {% if form.type.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.type.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.damage.label(class="form-control-label") }}
                {{ form.damage(class="form-control form-control-lg") }}

                {% if form.damage.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.damage.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
        {% else %}
            <div class = "plea">
                To Use the Register Attack function or to view your saved attacks, please <a class = "login-register-link" href="{{ url_for('users.login') }}">Log-In</a> or <a class = "login-register-link" href="{{ url_for('users.register') }}">Register!</a>
            </div>
        {% endif %}
    </div>
    
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}



<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form class="form-base" action="" method="post">
            <div class="row">
                <div class="col">
                    <h2 class = "form-title">Log In</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    If you <b>don't</b> have an account, then <a class = "login-register-link" href="{{ url_for('users.register') }}">Register!</a>
                </div>
            </div>
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/register.html
{% extends "header.html" %}
{% block content %}

<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form class = "form-base" action="" method="post">
            <div class="row">
                <div class="col">
                    <h2 class = "form-title">Register</h2>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    If you already have an account, then just <a class = "login-register-link" href="{{ url_for('users.login') }}">Log In!</a>
                </div>
            </div>




            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}